spring:
  datasource:
    url: jdbc:mysql://l01rds-study-users.cx4c86coqxvs.ap-northeast-2.rds.amazonaws.com:3306/login_study
    # url: jdbc:mysql://host.docker.internal:3306/login_study
    # 도커를 생성한 host 의 local 로 접속
    username: login_study_dev
    # 도커에서 내 컴퓨터의 mysql 로 접속하는 것도 외부에서 접속하는 것이기 때문에
    # login_study_dev@% 어디서든 접근가능하게 바꾼다.
    password: 12345678
server:
  port: 9999
logging:
  level:
    org:
      springframework:
        security: DEBUG